pipeline {
    agent any
    tools{
        jdk 'java 17' // Asumiendo que estás usando Java 17, asegúrate de que este nombre coincida con tu configuración de Jenkins
        maven 'maven'
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/NitroRyder/TingesoEntrega1']])
                dir('entrega1/entrega1'){ //entrega1/entrega1
                    bat 'mvn clean package'
                }
            }
        }

        stage('Build docker image'){
            steps{
                dir('entrega1/entrega1'){
                    bat 'docker build -t nitroryder/entrega1:latest .'
                }
            }
        }
        stage('Push image to Docker Hub'){
            steps{
                dir('entrega1/entrega1'){
                   withCredentials([string(credentialsId: 'dkrhubpassword', variable: 'dhpsw')]) {
                        bat 'docker login -u nitroryder -p %dhpsw%'
                   }
                   bat 'docker push nitroryder/entrega1:latest'
                }
            }
        }
    }
}